### PR TITLE
[MODULAR] Rogue Life Bestiary

### PR DESCRIPTION
**Pull request by ORCACommander**
## About The Pull Request

We need more cute and dangerous critters about our stations

## Why It's Good For The Game

Not everything that can be murdered should be Ian
resolves issue #23
resolves issue #22

## Changelog
:cl:
add: Opossum and Poppy
add: Red Panda and Zesty
/:cl:

### CODE REVIEW

**Comment by ORCACommander** [comment]
Not gonna port bumbles. Bumbles recently had a canceled pr upstream

**Comment by RogueStationAI** [comment]
#### Test Merge Deployed

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 329ec1032b9cb05ba6c4d0cb7b51867f359c85a0
Pull Request: 44c97b95fec58ee7f272de16e0094e61fd922446
Server: 3e698a5b261c74390ac70af90f0fa645fe30816a

**Comment by ORCACommander** [comment]
hmm not as many animals are missing as i thought

**Comment by RogueStationAI** [comment]
#### Test Merge Updated

##### Server Instance
Live Server - Rogue Station - Skyrat

##### Revision
Origin: 329ec1032b9cb05ba6c4d0cb7b51867f359c85a0
Pull Request: fa11c4c74a30314c02da534a435610a6072df47b
Server: 11e94c6e000f7d1e5a1c630b3e09e165a26bb2b4

**Comment by RogueStationAI** [comment]
#### Test Merge Removed

**Pull request merged**
